version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./sqlscripts/init_tables.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sqlscripts/dump/items.sql:/docker-entrypoint-initdb.d/init2.sql
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3590:3590"
