DROP TABLE IF EXISTS gameuser CASCADE;
DROP TABLE IF EXISTS gamesessiontoken CASCADE;
DROP TABLE IF EXISTS gamecharacter CASCADE;
DROP TABLE IF EXISTS gamecharactercurrency CASCADE;
DROP TABLE IF EXISTS gameitem CASCADE;
DROP TABLE IF EXISTS gameitemattribute CASCADE;
DROP TABLE IF EXISTS gameequipment CASCADE;
DROP TABLE IF EXISTS gameinventory CASCADE;
